"""Session domain public API."""

from core.chat.errors import ChatSessionError
from core.sessions.sessions import (
    CHANNEL_MESSAGE_NOTE_PREFIX,
    CONTINUATION_FILE_SUFFIX,
    FORK_SOURCE_META_KEY,
    SESSION_AUTO_TITLE_INITIALIZED_KEY,
    SESSION_AUTO_TITLE_KEY,
    SESSION_FILE_EXTENSION,
    SESSION_FORK_ALWAYS_STRIP_META_KEYS,
    SESSION_FORK_CROSS_AGENT_STRIP_META_KEYS,
    SESSION_MOVE_STRIP_META_KEYS,
    SKILL_AVAILABLE_NOTE_PREFIX,
    ChatSession,
    ChatSessionManager,
    SessionIdentityReferenceUpdate,
    is_channel_message_note,
    is_skill_available_note,
    is_skill_context_note,
    latest_project_tool_context_id,
    project_tool_context_id,
    skill_activation_names,
    skill_context_note_name,
    skill_context_note_payload,
    skill_tool_activation,
    skill_tool_activation_name,
)

__all__ = [
    "CHANNEL_MESSAGE_NOTE_PREFIX",
    "CONTINUATION_FILE_SUFFIX",
    "FORK_SOURCE_META_KEY",
    "SESSION_FILE_EXTENSION",
    "SESSION_AUTO_TITLE_INITIALIZED_KEY",
    "SESSION_AUTO_TITLE_KEY",
    "SESSION_FORK_ALWAYS_STRIP_META_KEYS",
    "SESSION_FORK_CROSS_AGENT_STRIP_META_KEYS",
    "SESSION_MOVE_STRIP_META_KEYS",
    "SKILL_AVAILABLE_NOTE_PREFIX",
    "ChatSession",
    "ChatSessionError",
    "ChatSessionManager",
    "SessionIdentityReferenceUpdate",
    "is_channel_message_note",
    "is_skill_available_note",
    "is_skill_context_note",
    "latest_project_tool_context_id",
    "project_tool_context_id",
    "skill_activation_names",
    "skill_context_note_name",
    "skill_context_note_payload",
    "skill_tool_activation",
    "skill_tool_activation_name",
]
