"""Stable support facade for the split server RPC test suites."""

from tests.server.rpc_test_support_common import (
    FAKE_REFRESH_MODEL_CALLS,
    FAKE_REFRESH_MODEL_KWARGS,
    FAKE_REFRESH_MODEL_PROVIDER_IDS,
    STUB_SUBAGENT_SETTING_FIELDS,
    EmptyStubModels,
    InstrumentedAgentDeleteLock,
    JsonObject,
    StubAgent,
    StubAgentResolver,
    StubAgents,
    StubModels,
    StubProject,
    StubProjects,
    StubProviders,
    _no_models_dev_fetch,
    fake_refresh_models,
    openrouter_provider,
    openrouter_provider_with_secondary_connection,
)
from tests.server.rpc_test_support_runtime import (
    RecordingCompactionService,
    ReloadableStubRuntimeSkills,
    StubAdapter,
    StubDelegateRun,
    StubProcessManager,
    StubPrompts,
    StubRuntime,
    StubSkill,
    StubSkills,
    StubStorage,
    make_state,
)

__all__ = [
    "FAKE_REFRESH_MODEL_CALLS",
    "FAKE_REFRESH_MODEL_KWARGS",
    "FAKE_REFRESH_MODEL_PROVIDER_IDS",
    "STUB_SUBAGENT_SETTING_FIELDS",
    "EmptyStubModels",
    "InstrumentedAgentDeleteLock",
    "JsonObject",
    "RecordingCompactionService",
    "ReloadableStubRuntimeSkills",
    "StubAdapter",
    "StubAgent",
    "StubAgentResolver",
    "StubAgents",
    "StubDelegateRun",
    "StubModels",
    "StubProcessManager",
    "StubProject",
    "StubProjects",
    "StubPrompts",
    "StubProviders",
    "StubRuntime",
    "StubSkill",
    "StubSkills",
    "StubStorage",
    "_no_models_dev_fetch",
    "fake_refresh_models",
    "make_state",
    "openrouter_provider",
    "openrouter_provider_with_secondary_connection",
]
