"""core.extensions public API."""

from core.extensions.extensions import (
    API_VERSION,
    CommandDeclaration,
    Deny,
    ExtensionAPI,
    ExtensionManifest,
    ExtensionRecord,
    ExtensionRegistrationIdentity,
    ExtensionRegistry,
    HookContext,
    Modify,
    PageDeclaration,
    PreparedSessionDelivery,
    PromptBlockDeclaration,
    Replace,
    SessionRequestContext,
    ToolBatchDecision,
    ToolCallDecision,
    ToolFamilyDeclaration,
    ToolResultValidator,
    invoke_extension_handler,
    purge_extension_modules,
)
from core.extensions.interactions import (
    RESERVED_INTERACTION_PREFIXES,
    RUN_TRIGGER_PREFIX,
    InteractionButton,
    InteractionEvent,
    InteractionHandlerDeclaration,
    InteractionResponder,
)
from core.extensions.settings_schema import (
    SettingsFieldDeclaration,
    parse_settings_fields,
    validate_extension_config,
)

__all__ = [
    "API_VERSION",
    "CommandDeclaration",
    "Deny",
    "ExtensionAPI",
    "ExtensionManifest",
    "ExtensionRegistrationIdentity",
    "ExtensionRecord",
    "ExtensionRegistry",
    "HookContext",
    "RESERVED_INTERACTION_PREFIXES",
    "RUN_TRIGGER_PREFIX",
    "InteractionButton",
    "InteractionEvent",
    "InteractionHandlerDeclaration",
    "InteractionResponder",
    "Modify",
    "PageDeclaration",
    "PreparedSessionDelivery",
    "ToolBatchDecision",
    "PromptBlockDeclaration",
    "Replace",
    "SettingsFieldDeclaration",
    "ToolCallDecision",
    "ToolFamilyDeclaration",
    "ToolResultValidator",
    "SessionRequestContext",
    "invoke_extension_handler",
    "parse_settings_fields",
    "purge_extension_modules",
    "validate_extension_config",
]
