// Public Timeline presentation surface; internal files own message, Tool,
// child-Run and activity projections without changing consumer imports.
export {
  toolRowFromEvent,
  toolStatusLabel,
  toolRowPresentation,
} from './chatTimelinePresentation/toolRows.js';
export {
  subAgentLastToolName,
  subAgentToolStatusLabel,
  isSubAgentSpawnTool,
  isStartingForegroundSubAgent,
  subAgentAgentId,
  subAgentEffectiveRunId,
  subAgentQueueItemId,
  resolveSubAgentCancelPlan,
  subAgentPreview,
  subAgentDotStatus,
  subAgentNavigationTarget,
  subAgentResultKey,
  subAgentResultEntryAllowsFetch,
  subAgentShouldFetchResult,
  subAgentNeedsStatusVerification,
  subAgentDisplayResult,
  subAgentResultTextFromMessages,
  subAgentResultData,
} from './chatTimelinePresentation/subagents.js';
export {
  visibleRunChildren,
  isRunChildWorking,
  reasoningDurationLabel,
  runFooterParts,
  runFooterNotice,
  liveClockCadenceMs,
  isRowCancellable,
  backgroundTasks,
  backgroundBashRowState,
  backgroundBashToolStatusLabel,
  backgroundBashDisplayResult,
  isReflectionRunKind,
  reflectionTaskRows,
  reflectionElapsedLabel,
} from './chatTimelinePresentation/activity.js';
export {
  runChangeStats,
  sessionChangeStats,
  changeStatsLabel,
  changeStatsParts,
  changedFilesCard,
} from './chatTimelinePresentation/changeStats.js';
export {
  isUserItem,
  isAssistantItem,
  shouldRenderMessage,
  labelForMessage,
  labelForEvent,
  textFromMessage,
  errorMessagePresentation,
  userContentBlocks,
  hasUserContentBlocks,
  isTextContentBlock,
  isMediaContentBlock,
  isImageMediaContentBlock,
  isFileContentBlock,
  isFileMentionContentBlock,
  fileMentionStatusLabel,
  attachmentUrlForBlock,
  attachmentFilename,
  imageReferenceLabel,
  attachmentPreviewLabel,
  hasReadableReasoning,
  hasAssistantContent,
  isReasoningOnlyAssistantMessage,
  messageFromEvent,
  toolCallFromEvent,
  textFromEvent,
  toolNameForEvent,
  toolResultValueForEvent,
  isTextToSpeechResult,
  speechArtifactFromResult,
  isTextToSpeechTool,
  speechArtifactFromTool,
  timestampForItem,
  groupTransientCards,
  takeoverSeparatorLabel,
  compactionSeparatorLabel,
  compactionSummaryText,
  avatarForItem,
  metaForEvent,
  isToolEvent,
  isFailedToolEvent,
  isTerminalEvent,
} from './chatTimelinePresentation/messages.js';
export {
  toolStatus,
  isToolPreparing,
  toolArguments,
  toolNameForRunTool,
} from './chatTimelinePresentation/toolFacts.js';
export {
  formatTime,
  formatDate,
  dateKeyForTimestamp,
} from './chatTimelinePresentation/time.js';
export { toolDetailPresentation } from '$lib/chatToolDetails.js';

export { reasoningSummaryTitle } from './chatTimelinePresentation/reasoning.js';
