// Public Projects surface. Internal modules own editor reconciliation,
// dialog workflows and pure form/team/scan projections.
export { createProjectsController } from './projectsView/controller.js';
export {
  createProjectEditForm,
  createProjectsState,
  FINDING_TYPE_SLUG_COLLISION,
  FINDING_TYPE_UNSLUGIFIABLE_NAME,
  FINDING_TYPE_BAD_MODEL,
  FINDING_TYPE_ORPHAN,
  FINDING_TYPE_UNAVAILABLE_TOOL,
  PROJECT_SOURCE_FORMATS,
  DEFAULT_PROJECT_SOURCE_FORMAT,
  PROJECT_THINKING_EFFORT_NO_DEFAULT,
  PROJECT_THINKING_EFFORT_OPTIONS,
  buildAddProjectPayload,
  buildManageProjectPayload,
  buildToolToggleList,
  normalizeSkillPool,
  buildSkillToggleSections,
  setListMembership,
  normalizeScanSkills,
  hasManageChanges,
  buildDefaultAgentOptions,
  normalizeDetectResult,
  presentFormats,
  shouldSuggestClaudeMd,
  needsRePoint,
  buildRePointPayload,
  normalizeProject,
  normalizeProjects,
  projectTeam,
  projectAgentTargetSummary,
  memberFieldIsOverridden,
  seedTeamOverrideDraft,
  normalizeOverrideTemperature,
  normalizeScanReport,
} from './projectsView/presentation.js';
