"""Tool registry, definitions, result envelopes, and execution scheduling."""

from core.tools.apply_patch import register_apply_patch_tool
from core.tools.availability import (
    TOOL_ACCESS_MODE_ALL,
    TOOL_ACCESS_MODE_NONE,
    TOOL_ACCESS_MODE_SELECTED,
    TOOL_ACCESS_MODES,
    TOOL_ACTIVATION_CONFIGURABLE,
    TOOL_ACTIVATION_FOLLOWS,
    TOOL_ACTIVATION_MEMORY_MODE,
    TOOL_ACTIVATION_SESSION_GRANT,
    TOOL_CONSTRAINT_IDENTITY_AGENT,
    TOOL_CONSTRAINT_IMAGE_FALLBACK_ROUTE,
    ToolAccess,
    ToolAccessResolution,
    memory_tool_enabled,
    normalize_tool_access,
    resolve_tool_access,
)
from core.tools.change_tracker import ChangeTracker
from core.tools.contracts import (
    ToolContract,
    ToolContractError,
    compile_tool_contract,
)
from core.tools.edit import (
    EditDialect,
    edit_dialect,
    edit_tool_siblings,
    known_edit_dialect,
    offer_edit_dialect,
    register_edit_tools,
)
from core.tools.file_state import (
    FileReadState,
    StaleReason,
)
from core.tools.image import (
    ANALYZE_IMAGE_TOOL_DESCRIPTION,
    ANALYZE_IMAGE_TOOL_NAME,
    ANALYZE_IMAGE_TOOL_PARAMETERS,
    IMAGE_GENERATION_TOOL_DESCRIPTION,
    IMAGE_GENERATION_TOOL_NAME,
    IMAGE_GENERATION_TOOL_PARAMETERS,
    register_analyze_image_tool,
    register_image_generation_tool,
)
from core.tools.media_generation import (
    GENERATE_MUSIC_PARAMETERS,
    GENERATE_MUSIC_TOOL_NAME,
    GENERATE_VIDEO_PARAMETERS,
    GENERATE_VIDEO_TOOL_NAME,
    register_generate_music_tool,
    register_generate_video_tool,
)
from core.tools.memory import (
    MEMORY_TOOL_DESCRIPTION,
    MEMORY_TOOL_NAME,
    MEMORY_TOOL_PARAMETERS,
    register_memory_tool,
)
from core.tools.model_names import (
    BASH_TOOL_NAME,
    called_tool_name,
    model_tool_name,
    registry_tool_name,
)
from core.tools.project import (
    PROJECT_PROMPT_BLOCK_HEADER,
    PROJECT_TOOL_DESCRIPTION,
    PROJECT_TOOL_NAME,
    PROJECT_TOOL_PARAMETERS,
    register_project_tool,
)
from core.tools.read import (
    READ_TOOL_DESCRIPTION,
    READ_TOOL_NAME,
    READ_TOOL_PARAMETERS,
    register_read_tool,
)
from core.tools.search_files import (
    SEARCH_FILES_TOOL_DESCRIPTION,
    SEARCH_FILES_TOOL_NAME,
    SEARCH_FILES_TOOL_PARAMETERS,
    register_search_files_tool,
)
from core.tools.session_search import (
    SESSION_SEARCH_TOOL_DESCRIPTION,
    SESSION_SEARCH_TOOL_NAME,
    SESSION_SEARCH_TOOL_PARAMETERS,
    register_session_search_tool,
)
from core.tools.shell import (
    SHELL_TOOL_DESCRIPTION,
    SHELL_TOOL_NAME,
    SHELL_TOOL_PARAMETERS,
    project_shell_tool_definitions,
    register_shell_tool,
)
from core.tools.skill import (
    SKILL_TOOL_DESCRIPTION,
    SKILL_TOOL_NAME,
    SKILL_TOOL_PARAMETERS,
    register_skill_tool,
)
from core.tools.skill_manage import (
    SKILL_MANAGE_TOOL_DESCRIPTION,
    SKILL_MANAGE_TOOL_NAME,
    SKILL_MANAGE_TOOL_PARAMETERS,
    register_skill_manage_tool,
)
from core.tools.speech import (
    TEXT_TO_SPEECH_TOOL_DESCRIPTION,
    TEXT_TO_SPEECH_TOOL_NAME,
    TEXT_TO_SPEECH_TOOL_PARAMETERS,
    register_text_to_speech_tool,
)
from core.tools.terminal import (
    TERMINAL_TOOL_DESCRIPTION,
    TERMINAL_TOOL_NAME,
    TERMINAL_TOOL_PARAMETERS,
    register_terminal_tool,
)
from core.tools.tools import (
    DEFAULT_TOOL_CONCURRENCY_LIMIT,
    READ_MEDIA_ARTIFACT_KIND,
    TOOL_ALLOWLIST_WILDCARD,
    DuplicateToolError,
    InvalidToolResultError,
    JsonObject,
    SessionToolUnavailableError,
    Tool,
    ToolCall,
    ToolCancellationHook,
    ToolContext,
    ToolDefinitionChangeNote,
    ToolDefinitionProfile,
    ToolDefinitionProfileContext,
    ToolDefinitionProfileResolver,
    ToolDisplay,
    ToolDisplayField,
    ToolDisplayPart,
    ToolEmitHook,
    ToolError,
    ToolExecutionConfig,
    ToolExecutor,
    ToolFamily,
    ToolHandler,
    ToolNotAllowedError,
    ToolNoteHook,
    ToolNotFoundError,
    ToolPromptBlockRegistry,
    ToolReadinessPredicate,
    ToolRegistry,
    ToolResultPersistedCallback,
    ToolSkillActivationHook,
    is_tool_result_envelope,
    read_media_artifact,
    result_count_fact_builder,
    tool_failure,
    tool_failure_for_exception,
    tool_is_ready,
    tool_success,
)
from core.tools.update_handoff import UpdateHandoffs
from core.tools.web_fetch import (
    WEB_FETCH_TOOL_DESCRIPTION,
    WEB_FETCH_TOOL_NAME,
    WEB_FETCH_TOOL_PARAMETERS,
    register_web_fetch_tool,
)
from core.tools.web_search import (
    WEB_SEARCH_TOOL_DESCRIPTION,
    WEB_SEARCH_TOOL_NAME,
    WEB_SEARCH_TOOL_PARAMETERS,
    register_web_search_tool,
)


def __getattr__(name: str) -> object:
    if name == "register_cron_tool":
        from core.tools.cron import register_cron_tool

        return register_cron_tool
    if name == "register_subagent_tools":
        from core.tools.subagent import register_subagent_tools

        return register_subagent_tools
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "SEARCH_FILES_TOOL_DESCRIPTION",
    "SEARCH_FILES_TOOL_NAME",
    "SEARCH_FILES_TOOL_PARAMETERS",
    "register_search_files_tool",
    "register_apply_patch_tool",
    "register_edit_tools",
    "EditDialect",
    "edit_dialect",
    "edit_tool_siblings",
    "known_edit_dialect",
    "offer_edit_dialect",
    "BASH_TOOL_NAME",
    "ANALYZE_IMAGE_TOOL_DESCRIPTION",
    "ANALYZE_IMAGE_TOOL_NAME",
    "ANALYZE_IMAGE_TOOL_PARAMETERS",
    "DEFAULT_TOOL_CONCURRENCY_LIMIT",
    "DuplicateToolError",
    "FileReadState",
    "StaleReason",
    "ChangeTracker",
    "IMAGE_GENERATION_TOOL_DESCRIPTION",
    "IMAGE_GENERATION_TOOL_NAME",
    "IMAGE_GENERATION_TOOL_PARAMETERS",
    "InvalidToolResultError",
    "JsonObject",
    "SessionToolUnavailableError",
    "MEMORY_TOOL_DESCRIPTION",
    "MEMORY_TOOL_NAME",
    "MEMORY_TOOL_PARAMETERS",
    "PROJECT_PROMPT_BLOCK_HEADER",
    "PROJECT_TOOL_DESCRIPTION",
    "PROJECT_TOOL_NAME",
    "PROJECT_TOOL_PARAMETERS",
    "READ_TOOL_DESCRIPTION",
    "READ_TOOL_NAME",
    "READ_TOOL_PARAMETERS",
    "SESSION_SEARCH_TOOL_DESCRIPTION",
    "SESSION_SEARCH_TOOL_NAME",
    "SESSION_SEARCH_TOOL_PARAMETERS",
    "SKILL_MANAGE_TOOL_DESCRIPTION",
    "SKILL_MANAGE_TOOL_NAME",
    "SKILL_MANAGE_TOOL_PARAMETERS",
    "SKILL_TOOL_DESCRIPTION",
    "SKILL_TOOL_NAME",
    "SKILL_TOOL_PARAMETERS",
    "TEXT_TO_SPEECH_TOOL_DESCRIPTION",
    "TEXT_TO_SPEECH_TOOL_NAME",
    "TEXT_TO_SPEECH_TOOL_PARAMETERS",
    "TERMINAL_TOOL_DESCRIPTION",
    "TERMINAL_TOOL_NAME",
    "TERMINAL_TOOL_PARAMETERS",
    "TOOL_ALLOWLIST_WILDCARD",
    "TOOL_ACCESS_MODE_ALL",
    "TOOL_ACCESS_MODE_NONE",
    "TOOL_ACCESS_MODE_SELECTED",
    "TOOL_ACCESS_MODES",
    "TOOL_ACTIVATION_CONFIGURABLE",
    "TOOL_ACTIVATION_FOLLOWS",
    "TOOL_ACTIVATION_MEMORY_MODE",
    "TOOL_ACTIVATION_SESSION_GRANT",
    "TOOL_CONSTRAINT_IDENTITY_AGENT",
    "TOOL_CONSTRAINT_IMAGE_FALLBACK_ROUTE",
    "Tool",
    "ToolAccess",
    "ToolAccessResolution",
    "ToolCall",
    "ToolContract",
    "ToolContractError",
    "ToolCancellationHook",
    "ToolContext",
    "ToolDefinitionChangeNote",
    "ToolDefinitionProfile",
    "ToolDefinitionProfileContext",
    "ToolDefinitionProfileResolver",
    "ToolDisplay",
    "ToolDisplayField",
    "ToolDisplayPart",
    "ToolEmitHook",
    "ToolError",
    "ToolExecutionConfig",
    "ToolExecutor",
    "ToolFamily",
    "ToolHandler",
    "ToolNoteHook",
    "ToolNotAllowedError",
    "ToolNotFoundError",
    "ToolPromptBlockRegistry",
    "ToolReadinessPredicate",
    "ToolRegistry",
    "ToolResultPersistedCallback",
    "ToolSkillActivationHook",
    "WEB_FETCH_TOOL_DESCRIPTION",
    "WEB_FETCH_TOOL_NAME",
    "WEB_FETCH_TOOL_PARAMETERS",
    "GENERATE_MUSIC_TOOL_NAME",
    "GENERATE_MUSIC_PARAMETERS",
    "GENERATE_VIDEO_PARAMETERS",
    "GENERATE_VIDEO_TOOL_NAME",
    "WEB_SEARCH_TOOL_DESCRIPTION",
    "WEB_SEARCH_TOOL_NAME",
    "WEB_SEARCH_TOOL_PARAMETERS",
    "UpdateHandoffs",
    "SHELL_TOOL_DESCRIPTION",
    "SHELL_TOOL_NAME",
    "SHELL_TOOL_PARAMETERS",
    "project_shell_tool_definitions",
    "register_shell_tool",
    "READ_MEDIA_ARTIFACT_KIND",
    "is_tool_result_envelope",
    "read_media_artifact",
    "result_count_fact_builder",
    "register_analyze_image_tool",
    "register_cron_tool",
    "register_generate_music_tool",
    "register_generate_video_tool",
    "register_memory_tool",
    "register_project_tool",
    "register_read_tool",
    "register_session_search_tool",
    "register_skill_manage_tool",
    "register_skill_tool",
    "register_subagent_tools",
    "register_text_to_speech_tool",
    "register_terminal_tool",
    "register_image_generation_tool",
    "register_web_fetch_tool",
    "register_web_search_tool",
    "tool_failure",
    "tool_failure_for_exception",
    "tool_is_ready",
    "tool_success",
    "compile_tool_contract",
    "memory_tool_enabled",
    "normalize_tool_access",
    "resolve_tool_access",
    "called_tool_name",
    "model_tool_name",
    "registry_tool_name",
]
