"""Settings domain public API."""

from core.config_validation import (
    JsonDiagnostic,
    JsonValidationReport,
    format_report_diagnostics,
)
from core.settings.normalizers import (
    DEFAULT_APPEARANCE_LANGUAGE,
    DEFAULT_RECALL_SETTINGS,
    DEFAULT_SESSION_TITLE_SETTINGS,
    SUPPORTED_APPEARANCE_LANGUAGES,
)
from core.settings.settings import (
    AGENT_DEFAULT_FIELDS,
    AGENT_ID_PATTERN,
    ALLOWED_THINKING_EFFORTS,
    DEFAULT_APPEARANCE_CHAT_WIDTH,
    DEFAULT_PROJECT_SOURCE_FORMAT,
    MAX_TEMPERATURE,
    MIN_TEMPERATURE,
    PROJECT_ID_PATTERN,
    PROJECT_SOURCE_FORMATS,
    PROJECT_TOOL_ALLOWLIST_WILDCARD,
    SUPPORTED_APPEARANCE_CHAT_WIDTHS,
    SettingsValidationError,
    is_valid_agent_id,
    is_valid_project_id,
    parse_settings_update,
    validate_temperature,
    validate_thinking_effort,
)
from core.settings.validation import (
    SettingsDiagnostic,
    SettingsValidationReport,
    load_runtime_settings_json,
    load_validated_settings_json,
    validate_data_dir_config,
    validate_settings_data,
    validate_settings_file,
)

__all__ = [
    "AGENT_DEFAULT_FIELDS",
    "AGENT_ID_PATTERN",
    "ALLOWED_THINKING_EFFORTS",
    "DEFAULT_APPEARANCE_CHAT_WIDTH",
    "DEFAULT_APPEARANCE_LANGUAGE",
    "DEFAULT_PROJECT_SOURCE_FORMAT",
    "DEFAULT_RECALL_SETTINGS",
    "DEFAULT_SESSION_TITLE_SETTINGS",
    "JsonDiagnostic",
    "JsonValidationReport",
    "MAX_TEMPERATURE",
    "MIN_TEMPERATURE",
    "PROJECT_ID_PATTERN",
    "PROJECT_SOURCE_FORMATS",
    "PROJECT_TOOL_ALLOWLIST_WILDCARD",
    "SUPPORTED_APPEARANCE_CHAT_WIDTHS",
    "SUPPORTED_APPEARANCE_LANGUAGES",
    "SettingsDiagnostic",
    "SettingsValidationError",
    "SettingsValidationReport",
    "format_report_diagnostics",
    "is_valid_agent_id",
    "is_valid_project_id",
    "load_runtime_settings_json",
    "load_validated_settings_json",
    "parse_settings_update",
    "validate_data_dir_config",
    "validate_settings_data",
    "validate_settings_file",
    "validate_temperature",
    "validate_thinking_effort",
]
