"""History shaping, wire carriers and response measurements for the exact probe."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any

from core.chat.messages import ChatMessage
from core.chat.wire_shaping import _assemble_request_history, _assistant_continuation_dict
from core.providers.reasoning import model_reasoning_supported

TOOL_DEFINITION: dict[str, Any] = {
    "type": "function",
    "function": {
        "name": "get_weather",
        "description": "Get the current weather in a city",
        "parameters": {
            "type": "object",
            "properties": {"city": {"type": "string"}},
            "required": ["city"],
        },
    },
}


@dataclass(frozen=True)
class TurnResult:
    content: str
    reasoning: str
    reasoning_meta: dict[str, Any] | None
    tool_calls: list[dict[str, Any]]
    input_tokens: int | None


def _make_secret() -> str:
    """Random non-numeric secret token the model cannot guess or prefer.

    Numeric 5-digit secrets turned out to be unreliable probe material: the
    models repeatedly produced and answered with the same numbers (48291,
    48372 across runs), which made recall results ambiguous. A 12-character
    base-36 token is planted by the probe itself (never generated by the
    model), so a recall can only come from the carrier (or the control).
    """
    import random

    alphabet = "abcdefghijkmnpqrstuvwxyz23456789"  # no ambiguous chars
    return "".join(random.SystemRandom().choice(alphabet) for _ in range(12))


def _secret_reasoning(secret: str) -> str:
    return f"The secret token is {secret}. Remember it for later questions."


def _extract_openai_message(message: dict[str, Any]) -> TurnResult:
    reasoning = ""
    for field in ("reasoning", "reasoning_content", "thinking"):
        value = message.get(field)
        if isinstance(value, str) and value:
            reasoning = value
            break
    usage = message.get("usage")
    input_tokens = usage.get("input_tokens") if isinstance(usage, dict) else None
    reasoning_meta = message.get("reasoning_meta")
    return TurnResult(
        content=message.get("content") or "",
        reasoning=reasoning,
        reasoning_meta=dict(reasoning_meta) if isinstance(reasoning_meta, dict) else None,
        tool_calls=message.get("tool_calls") or [],
        input_tokens=input_tokens if isinstance(input_tokens, int) else None,
    )


def _find_secret(reasoning: str) -> str | None:
    numbers = re.findall(r"\b\d{5}\b", reasoning)
    return numbers[0] if numbers else None


def _replay_tool_calls(tool_calls: list[dict[str, Any]], wire: str) -> list[dict[str, Any]]:
    replayed: list[dict[str, Any]] = []
    for position, call in enumerate(tool_calls):
        if not isinstance(call, dict):
            continue
        function = call.get("function", {})
        if not isinstance(function, dict):
            function = {}
        name = function.get("name") or ""
        arguments = function.get("arguments") or {}
        if wire == "openai":
            if isinstance(arguments, dict):
                arguments = json.dumps(arguments, separators=(",", ":"))
            replayed.append(
                {
                    "id": call.get("id") or f"call_{position}",
                    "type": "function",
                    "function": {"name": name, "arguments": arguments},
                }
            )
        else:
            if isinstance(arguments, str):
                try:
                    arguments = json.loads(arguments)
                except json.JSONDecodeError:
                    arguments = {}
            replayed.append(
                {
                    "id": call.get("id") or f"call_{position}",
                    "function": {"name": name, "arguments": arguments},
                }
            )
    return replayed


async def _run_turn(
    adapter: Any,
    model_id: str,
    messages: list[dict[str, Any]],
    *,
    tools: list[dict[str, Any]] | None,
    effort: str = "max",
) -> TurnResult:
    kwargs: dict[str, Any] = {"tools": tools} if tools else {}
    raw = await adapter.send(
        messages,
        model_id=model_id,
        temperature=1.0,
        thinking_effort=effort,
        **adapter.request_context_kwargs(agent_id="model-audit", session_id="reasoning-replay"),
        **kwargs,
    )
    normalized = adapter.normalize_response(raw, model_id=model_id)
    message = normalized
    return _extract_openai_message(message)


def _build_exact_payload(
    adapter: Any,
    messages: list[dict[str, Any]],
    model_id: str,
    *,
    tools: list[dict[str, Any]] | None,
    effort: str,
) -> dict[str, Any]:
    """Build the payload for the same model-selected wire used by ``send``."""

    protocol_resolver = getattr(adapter, "_model_protocol", None)
    protocol = protocol_resolver(model_id) if callable(protocol_resolver) else "openai"
    kwargs: dict[str, Any] = {
        "temperature": 1.0,
        "thinking_effort": effort,
    }
    if tools:
        kwargs["tools"] = tools
    if protocol == "anthropic":
        return dict(adapter._messages._build_payload(messages, model_id, **kwargs))
    if protocol == "responses":
        return dict(adapter._build_responses_payload(messages, model_id=model_id, **kwargs))
    return dict(adapter._build_payload(messages, model_id, **kwargs))


def _assistant_wire_carriers(payload: dict[str, Any]) -> list[str]:
    """Describe reasoning carriers in final Assistant history wire items."""

    carriers: list[str] = []
    for message in payload.get("messages", []):
        if not isinstance(message, dict) or message.get("role") != "assistant":
            continue
        for key in ("reasoning", "reasoning_content", "reasoning_details", "thinking"):
            if key in message:
                carriers.append(key)
        content = message.get("content")
        if isinstance(content, list):
            for block in content:
                if not isinstance(block, dict):
                    continue
                block_type = block.get("type")
                if block_type in {"thinking", "redacted_thinking"}:
                    carriers.append(f"content:{block_type}")
    for item in payload.get("input", []):
        if isinstance(item, dict) and item.get("type") == "reasoning":
            carriers.append("input:reasoning")
    return sorted(carriers)


def _shape_history(
    messages: list[ChatMessage],
    *,
    replay_policy: str,
    agent_model: str,
) -> list[dict[str, Any]]:
    """Shape persisted history exactly like the chat loop (``_assemble_request_history``)."""
    return _assemble_request_history(
        messages,
        replay_policy=replay_policy,  # type: ignore[arg-type]
        agent_model=agent_model,
    )


def _shape_live_turn(
    message: ChatMessage,
    *,
    replay_policy: str,
) -> dict[str, Any]:
    """Shape the live current-run assistant turn (``_assistant_continuation_dict``)."""
    return _assistant_continuation_dict(
        message,
        replay_policy=replay_policy,  # type: ignore[arg-type]
    )


def _responses_output_items(message: dict[str, Any]) -> list[dict[str, Any]]:
    reasoning_meta = message.get("reasoning_meta")
    if not isinstance(reasoning_meta, dict):
        return []
    output = reasoning_meta.get("response_output")
    if not isinstance(output, list) or not all(isinstance(item, dict) for item in output):
        return []
    return output


def _encrypted_reasoning_expected(adapter: Any, model_id: str) -> bool:
    return model_reasoning_supported(getattr(adapter, "_model_lookup", None), model_id) is not False


def _client_tools_expected(adapter: Any, model_id: str) -> bool:
    model_lookup = getattr(adapter, "_model_lookup", None)
    if model_lookup is None:
        return True
    model = model_lookup(model_id.split("::", 1)[0])
    return model is None or model.capabilities.tools


def _shape_session(
    messages: list[ChatMessage],
    *,
    policy: str,
    agent_model: str,
    live_assistant: ChatMessage | None = None,
) -> list[dict[str, Any]]:
    """Shape a session exactly like the chat loop does.

    Persisted session history runs through ``_assemble_request_history``,
    which strips reasoning under ``current_run``/``none``. The live
    current-run assistant turn is the freshly generated tool-call turn: the
    chat loop carries its continuation form (``_assistant_continuation_dict``,
    which keeps reasoning under ``current_run``/``full_history`` and only
    strips it under ``none``) at the assistant's position — before its tool
    results. The history-shaped assistant entry (stripped) is replaced by the
    continuation form, keeping the request order
    [user, assistant, tool, user].
    """
    wire_messages = _assemble_request_history(
        messages,
        replay_policy=policy,  # type: ignore[arg-type]
        agent_model=agent_model,
    )
    if live_assistant is None:
        return wire_messages
    live = _assistant_continuation_dict(
        live_assistant,
        replay_policy=policy,  # type: ignore[arg-type]
    )
    for index, message in enumerate(wire_messages):
        if message.get("role") == "assistant" and message.get("tool_calls"):
            wire_messages[index] = live
            return wire_messages
    return wire_messages


def _wire_carrier_present(
    wire_messages: list[dict[str, Any]],
) -> bool:
    """Report whether the shaped history carries canonical assistant reasoning.

    The shaped messages are canonical (the adapter converts ``reasoning`` to
    the provider wire field in ``_format_assistant_message``), so the check
    looks for the canonical ``reasoning`` field.
    """
    for message in wire_messages:
        if message.get("role") != "assistant":
            continue
        value = message.get("reasoning")
        reasoning_meta = message.get("reasoning_meta")
        if (isinstance(value, str) and value) or (
            isinstance(reasoning_meta, dict) and reasoning_meta
        ):
            return True
    return False


def _build_tool_calls(tool_calls: list[dict[str, Any]]) -> list[Any]:
    from core.chat.messages import ToolCall

    built: list[Any] = []
    for position, call in enumerate(tool_calls):
        if not isinstance(call, dict):
            continue
        function = call.get("function", {})
        if not isinstance(function, dict):
            function = {}
        name = function.get("name") or call.get("name") or ""
        arguments = function.get("arguments", call.get("arguments"))
        if isinstance(arguments, str):
            try:
                arguments = json.loads(arguments)
            except json.JSONDecodeError:
                arguments = {}
        if not isinstance(arguments, dict):
            arguments = {}
        built.append(
            ToolCall(
                id=call.get("id") or f"call_{position}",
                name=name,
                arguments=arguments,
            )
        )
    return built
