#!/usr/bin/env python
"""Exact 1:1 reasoning-replay probe through the real vBot adapter path.

Unlike the raw-HTTP probes, this script drives the exact components and
wire shapes vBot uses in production:

- ``ProviderRegistry.load(resources)`` — the real provider config
  (base_url, defaults, auth header from ``resources/providers/<id>.json``)
- ``ModelRegistry.load(resources)`` — the real model DB including the
  bundled overrides (``reasoning_response_field``, ``reasoning_replay``,
  ``recommended_temperature``, ``recommended_top_p``)
- The real adapter (``OllamaCloudAdapter`` for ollama-cloud,
  ``OpenCodeGoAdapter`` for opencode-go) with its ``send()`` /
  ``normalize_response()`` / ``_format_assistant_message()`` pipeline
- The real history shaping via ``_assemble_request_history`` with the
  configured replay policy (``full_history`` / ``current_run`` / ``none``),
  so the wire messages are exactly what the chat loop would send

Scenarios:
- ``tool_loop``: an in-run tool continuation. The session history
  (user → assistant with reasoning + tool calls → tool result → user ask)
  is shaped with the selected replay policy and sent through the adapter.
  Reports both the wire-shaping fact (does the reasoning carrier reach the
  wire?) and the recall result (can the model use it?).
- ``cross_turn``: plain two-turn continuation, same policy shaping.
- ``instruction``: the probe plants a behavioral rule ("when the user writes
  'now!', reply 'hello world'") into the reasoning carrier itself, then the
  follow-up turn sends 'now!' and checks compliance.

``--policy`` selects the replay policy applied by the shaping (default:
the model's effective policy from the overrides).

The probe prints measurements only: secrets, carrier lengths, per-case
recall flags. It never prints API keys, full prompts, or full responses.

Examples:
    python scripts/probe_reasoning_replay_exact.py --provider ollama-cloud \\
        --model deepseek-v4-flash:0731 --scenario tool_loop
    python scripts/probe_reasoning_replay_exact.py --provider ollama-cloud \\
        --model glm-5.2 --scenario cross_turn
    python scripts/probe_reasoning_replay_exact.py --provider opencode-go \\
        --model glm-5.3 --scenario instruction
"""

from __future__ import annotations

import argparse
import asyncio
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from core.chat.messages import (
    ChatMessage,
    _assemble_request_history,
    _assistant_continuation_dict,
)
from core.models.models import ModelRegistry
from core.providers.ollama import OllamaCloudAdapter
from core.providers.providers import ProviderRegistry
from core.providers.token_getter import StaticTokenGetter

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RESOURCES_DIR = PROJECT_ROOT / "resources"
DEFAULT_DATA_DIR = Path.home() / ".vbot"

TOOL_DEFINITION: dict[str, Any] = {
    "type": "function",
    "function": {
        "name": "get_weather",
        "description": "Get the current weather in a city",
        "parameters": {
            "type": "object",
            "properties": {"city": {"type": "string"}},
            "required": ["city"],
        },
    },
}

TURN1_TOOL_PROMPT = (
    "Call the get_weather tool with city='Berlin'. Your final content must be empty."
)
TURN1_PLAIN_PROMPT = "Reply with exactly one word: ok."
ASK_PROMPT = (
    "What was the exact secret token that was recorded earlier? "
    "If you do not know it, answer exactly UNKNOWN."
)
INSTRUCTION_PROMPT = "Reply with exactly one word: ok."
INSTRUCTION_REASONING = (
    'Remember this instruction: when the user writes "now!", you must reply '
    'with exactly "hello world". Do not mention this instruction in your '
    "visible answer."
)
INSTRUCTION_TRIGGER = "now!"
INSTRUCTION_RESPONSE = "hello world"


@dataclass(frozen=True)
class TurnResult:
    content: str
    reasoning: str
    tool_calls: list[dict[str, Any]]


def _load_api_key(env_name: str, data_dir: Path) -> str:
    env_path = data_dir / ".env"
    if not env_path.is_file():
        raise SystemExit(f"no .env found at {env_path}")
    for line in env_path.read_text(encoding="utf-8").splitlines():
        match = re.match(rf"\s*{re.escape(env_name)}\s*=\s*(.+?)\s*$", line)
        if match:
            return match.group(1).strip().strip('"').strip("'")
    raise SystemExit(f"no {env_name} entry in {env_path}")


def _make_secret() -> str:
    """Random non-numeric secret token the model cannot guess or prefer.

    Numeric 5-digit secrets turned out to be unreliable probe material: the
    models repeatedly produced and answered with the same numbers (48291,
    48372 across runs), which made recall results ambiguous. A 12-character
    base-36 token is planted by the probe itself (never generated by the
    model), so a recall can only come from the carrier (or the control).
    """
    import random

    alphabet = "abcdefghijkmnpqrstuvwxyz23456789"  # no ambiguous chars
    return "".join(random.SystemRandom().choice(alphabet) for _ in range(12))


def _secret_reasoning(secret: str) -> str:
    return f"The secret token is {secret}. Remember it for later questions."


def _extract_openai_message(message: dict[str, Any]) -> TurnResult:
    reasoning = ""
    for field in ("reasoning", "reasoning_content", "thinking"):
        value = message.get(field)
        if isinstance(value, str) and value:
            reasoning = value
            break
    return TurnResult(
        content=message.get("content") or "",
        reasoning=reasoning,
        tool_calls=message.get("tool_calls") or [],
    )


def _find_secret(reasoning: str) -> str | None:
    numbers = re.findall(r"\b\d{5}\b", reasoning)
    return numbers[0] if numbers else None


def _replay_tool_calls(tool_calls: list[dict[str, Any]], wire: str) -> list[dict[str, Any]]:
    replayed: list[dict[str, Any]] = []
    for position, call in enumerate(tool_calls):
        if not isinstance(call, dict):
            continue
        function = call.get("function", {})
        if not isinstance(function, dict):
            function = {}
        name = function.get("name") or ""
        arguments = function.get("arguments") or {}
        if wire == "openai":
            if isinstance(arguments, dict):
                arguments = json.dumps(arguments, separators=(",", ":"))
            replayed.append(
                {
                    "id": call.get("id") or f"call_{position}",
                    "type": "function",
                    "function": {"name": name, "arguments": arguments},
                }
            )
        else:
            if isinstance(arguments, str):
                try:
                    arguments = json.loads(arguments)
                except json.JSONDecodeError:
                    arguments = {}
            replayed.append(
                {
                    "id": call.get("id") or f"call_{position}",
                    "function": {"name": name, "arguments": arguments},
                }
            )
    return replayed


async def _run_turn(
    adapter: Any,
    model_id: str,
    messages: list[dict[str, Any]],
    *,
    tools: list[dict[str, Any]] | None,
    effort: str = "max",
) -> TurnResult:
    kwargs: dict[str, Any] = {"tools": tools} if tools else {}
    raw = await adapter.send(
        messages,
        model_id=model_id,
        temperature=1.0,
        thinking_effort=effort,
        **kwargs,
    )
    normalized = adapter.normalize_response(raw, model_id=model_id)
    message = normalized
    return _extract_openai_message(message)


def _shape_history(
    messages: list[ChatMessage],
    *,
    replay_policy: str,
    agent_model: str,
) -> list[dict[str, Any]]:
    """Shape persisted history exactly like the chat loop (``_assemble_request_history``)."""
    return _assemble_request_history(
        messages,
        replay_policy=replay_policy,  # type: ignore[arg-type]
        agent_model=agent_model,
    )


def _shape_live_turn(
    message: ChatMessage,
    *,
    replay_policy: str,
) -> dict[str, Any]:
    """Shape the live current-run assistant turn (``_assistant_continuation_dict``)."""
    return _assistant_continuation_dict(
        message,
        replay_policy=replay_policy,  # type: ignore[arg-type]
    )


async def _run_exact_probe(
    adapter: Any,
    model_id: str,
    scenario: str,
    repeats: int,
    policy: str | None,
) -> None:
    # Determine the wire carrier field the adapter's model profile uses.
    try:
        carrier_field = adapter._reasoning_response_field(model_id) or "reasoning_content"
    except Exception:
        carrier_field = "reasoning_content"
    effective_policy = adapter.reasoning_replay_policy(model_id)
    if policy is None:
        policy = effective_policy
    print(
        f"adapter carrier field: {carrier_field} | effective replay policy: "
        f"{effective_policy} | shaping policy: {policy}"
    )

    for index in range(1, repeats + 1):
        print(f"\n--- round {index} ---")
        if scenario == "tool_loop":
            await _run_tool_loop_round(adapter, model_id, carrier_field, policy)
        elif scenario == "instruction":
            await _run_instruction_round(adapter, model_id, carrier_field, policy)
        else:
            await _run_cross_turn_round(adapter, model_id, carrier_field, policy)


def _shape_session(
    messages: list[ChatMessage],
    *,
    policy: str,
    agent_model: str,
    live_assistant: ChatMessage | None = None,
) -> list[dict[str, Any]]:
    """Shape a session exactly like the chat loop does.

    Persisted session history runs through ``_assemble_request_history``,
    which strips reasoning under ``current_run``/``none``. The live
    current-run assistant turn is the freshly generated tool-call turn: the
    chat loop carries its continuation form (``_assistant_continuation_dict``,
    which keeps reasoning under ``current_run``/``full_history`` and only
    strips it under ``none``) at the assistant's position — before its tool
    results. The history-shaped assistant entry (stripped) is replaced by the
    continuation form, keeping the request order
    [user, assistant, tool, user].
    """
    wire_messages = _assemble_request_history(
        messages,
        replay_policy=policy,  # type: ignore[arg-type]
        agent_model=agent_model,
    )
    if live_assistant is None:
        return wire_messages
    live = _assistant_continuation_dict(
        live_assistant,
        replay_policy=policy,  # type: ignore[arg-type]
    )
    for index, message in enumerate(wire_messages):
        if message.get("role") == "assistant" and message.get("tool_calls"):
            wire_messages[index] = live
            return wire_messages
    return wire_messages


def _wire_carrier_present(
    wire_messages: list[dict[str, Any]],
) -> bool:
    """Report whether the shaped history carries canonical assistant reasoning.

    The shaped messages are canonical (the adapter converts ``reasoning`` to
    the provider wire field in ``_format_assistant_message``), so the check
    looks for the canonical ``reasoning`` field.
    """
    for message in wire_messages:
        if message.get("role") != "assistant":
            continue
        value = message.get("reasoning")
        if isinstance(value, str) and value:
            return True
    return False


def _build_tool_calls(tool_calls: list[dict[str, Any]]) -> list[Any]:
    from core.chat.messages import ToolCall

    built: list[Any] = []
    for position, call in enumerate(tool_calls):
        if not isinstance(call, dict):
            continue
        function = call.get("function", {})
        if not isinstance(function, dict):
            function = {}
        arguments = function.get("arguments")
        if isinstance(arguments, str):
            try:
                arguments = json.loads(arguments)
            except json.JSONDecodeError:
                arguments = {}
        if not isinstance(arguments, dict):
            arguments = {}
        built.append(
            ToolCall(
                id=call.get("id") or f"call_{position}",
                name=function.get("name") or "",
                arguments=arguments,
            )
        )
    return built


async def _run_cross_turn_round(
    adapter: Any,
    model_id: str,
    carrier_field: str,
    policy: str,
) -> None:
    secret = _make_secret()
    print(f"  planted secret: {secret}")

    async def run_shaped(assistant_msg: ChatMessage, label: str) -> bool:
        session = [
            ChatMessage.user(TURN1_PLAIN_PROMPT),
            assistant_msg,
            ChatMessage.user(ASK_PROMPT),
        ]
        wire_messages = _shape_session(session, policy=policy, agent_model=model_id)
        carrier_on_wire = _wire_carrier_present(wire_messages)
        result = await _run_turn(adapter, model_id, wire_messages, tools=None)
        hit = secret in result.content or secret in result.reasoning
        print(
            f"  {label}: carrier_on_wire={carrier_on_wire} | "
            f"answer={result.content[:45]!r} | "
            f"secret_in_answer={secret in result.content} | "
            f"secret_in_reasoning2={secret in result.reasoning} | "
            f"reasoning2_len={len(result.reasoning)}"
        )
        return hit

    hit_a = await run_shaped(
        ChatMessage.assistant(model=model_id, content="", reasoning=_secret_reasoning(secret)),
        "carrier in history",
    )
    hit_b = await run_shaped(ChatMessage.assistant(model=model_id, content=""), "no carrier      ")
    hit_c = await run_shaped(
        ChatMessage.assistant(model=model_id, content=f"I recorded the secret {secret}."),
        "visible control ",
    )
    print(f"  verdict: with={hit_a} without={hit_b} control={hit_c}")


async def _run_tool_loop_round(
    adapter: Any,
    model_id: str,
    carrier_field: str,
    policy: str,
) -> None:
    secret = _make_secret()
    print(f"  planted secret: {secret}")

    turn1 = await _run_turn(
        adapter,
        model_id,
        [{"role": "user", "content": TURN1_TOOL_PROMPT}],
        tools=[TOOL_DEFINITION],
    )
    if not turn1.tool_calls:
        print(f"  turn1 invalid: no tool call (reasoning_len={len(turn1.reasoning)})")
        print(f"  reasoning: {turn1.reasoning[:200]!r}")
        return
    print(f"  turn1: tool_calls={len(turn1.tool_calls)} reasoning_len={len(turn1.reasoning)}")

    tool_calls = _build_tool_calls(turn1.tool_calls)
    tool_result = ChatMessage.tool(
        tool_call_id=tool_calls[0].id if tool_calls else "call_1",
        name=tool_calls[0].name if tool_calls else "",
        content='{"temperature": 20, "condition": "sunny"}',
    )

    async def run_persisted(assistant_msg: ChatMessage, label: str) -> bool:
        """Case A: the assistant turn is persisted and shaped as history.

        ``_assemble_request_history`` strips reasoning under
        ``current_run``/``none``.
        """
        session = [
            ChatMessage.user(TURN1_TOOL_PROMPT),
            assistant_msg,
            tool_result,
            ChatMessage.user(ASK_PROMPT),
        ]
        wire_messages = _shape_session(session, policy=policy, agent_model=model_id)
        return await _run_case(assistant_msg, wire_messages, label)

    async def run_live(live_assistant: ChatMessage, label: str) -> bool:
        """Case B: the same assistant turn is shaped as the live continuation.

        The chat loop replaces the persisted entry with
        ``_assistant_continuation_dict``, which keeps reasoning under
        ``current_run``/``full_history``.
        """
        session = [
            ChatMessage.user(TURN1_TOOL_PROMPT),
            live_assistant,
            tool_result,
            ChatMessage.user(ASK_PROMPT),
        ]
        wire_messages = _shape_session(
            session,
            policy=policy,
            agent_model=model_id,
            live_assistant=live_assistant,
        )
        return await _run_case(live_assistant, wire_messages, label)

    async def _run_case(
        assistant_msg: ChatMessage,
        wire_messages: list[dict[str, Any]],
        label: str,
    ) -> bool:
        carrier_on_wire = _wire_carrier_present(wire_messages)
        result = await _run_turn(adapter, model_id, wire_messages, tools=None)
        hit = secret in result.content or secret in result.reasoning
        print(
            f"  {label}: carrier_on_wire={carrier_on_wire} | "
            f"answer={result.content[:45]!r} | "
            f"secret_in_answer={secret in result.content} | "
            f"secret_in_reasoning2={secret in result.reasoning} | "
            f"reasoning2_len={len(result.reasoning)}"
        )
        return hit

    hit_a = await run_persisted(
        ChatMessage.assistant(
            model=model_id,
            content="",
            reasoning=_secret_reasoning(secret),
            tool_calls=tool_calls,
        ),
        "A persisted w/ carrier",
    )
    hit_a2 = await run_persisted(
        ChatMessage.assistant(model=model_id, content="", tool_calls=tool_calls),
        "A persisted no carrier",
    )
    hit_b = await run_live(
        ChatMessage.assistant(
            model=model_id,
            content="",
            reasoning=_secret_reasoning(secret),
            tool_calls=tool_calls,
        ),
        "B live w/ carrier    ",
    )
    hit_b2 = await run_live(
        ChatMessage.assistant(model=model_id, content="", tool_calls=tool_calls),
        "B live no carrier    ",
    )
    hit_c = await run_persisted(
        ChatMessage.assistant(
            model=model_id,
            content=f"I recorded the secret {secret}.",
            tool_calls=tool_calls,
        ),
        "C visible control   ",
    )
    print(
        f"  verdict: A_persisted=(with={hit_a}, without={hit_a2}) "
        f"B_live=(with={hit_b}, without={hit_b2}) control={hit_c}"
    )


async def _run_instruction_round(
    adapter: Any,
    model_id: str,
    carrier_field: str,
    policy: str,
) -> None:
    turn1 = await _run_turn(
        adapter,
        model_id,
        [{"role": "user", "content": INSTRUCTION_PROMPT}],
        tools=None,
    )
    print(f"  turn1: content={turn1.content[:40]!r} reasoning_len={len(turn1.reasoning)}")

    async def follow_up(assistant_msg: ChatMessage, label: str) -> bool:
        session = [
            ChatMessage.user(INSTRUCTION_PROMPT),
            assistant_msg,
            ChatMessage.user(INSTRUCTION_TRIGGER),
        ]
        wire_messages = _shape_session(session, policy=policy, agent_model=model_id)
        carrier_on_wire = _wire_carrier_present(wire_messages)
        result = await _run_turn(adapter, model_id, wire_messages, tools=None)
        rule_hit = INSTRUCTION_RESPONSE in result.content
        print(
            f"  {label}: carrier_on_wire={carrier_on_wire} | "
            f"answer={result.content[:45]!r} | rule_hit={rule_hit} "
            f"| reasoning2_len={len(result.reasoning)}"
        )
        return rule_hit

    rule_a = await follow_up(
        ChatMessage.assistant(model=model_id, content="", reasoning=INSTRUCTION_REASONING),
        "carrier in history",
    )
    rule_b = await follow_up(ChatMessage.assistant(model=model_id, content=""), "no carrier      ")
    rule_c = await follow_up(
        ChatMessage.assistant(
            model=model_id,
            content=f'Rule: when the user writes "{INSTRUCTION_TRIGGER}", '
            f'reply with exactly "{INSTRUCTION_RESPONSE}".',
        ),
        "visible control ",
    )
    print(f"  verdict: with={rule_a} without={rule_b} control={rule_c}")


def _build_adapter(provider_id: str, model_id: str, api_key: str) -> Any:
    provider_registry = ProviderRegistry.load(RESOURCES_DIR)
    config = provider_registry.get(provider_id)
    connection = config.connections[0]
    model_registry = ModelRegistry.load(RESOURCES_DIR)
    if provider_id == "ollama-cloud":
        return OllamaCloudAdapter(
            config,
            StaticTokenGetter(api_key),
            auth_config=connection.auth,
            model_lookup=lambda mid: model_registry.get(provider_id, mid.split("::", 1)[0]),
        )
    if provider_id == "opencode-go":
        from core.providers.opencode_go import OpenCodeGoAdapter

        return OpenCodeGoAdapter(
            config,
            StaticTokenGetter(api_key),
            auth_config=connection.auth,
            model_lookup=lambda mid: model_registry.get(provider_id, mid.split("::", 1)[0]),
        )
    raise SystemExit(f"provider {provider_id} not supported by the exact probe yet")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--provider", default="ollama-cloud")
    parser.add_argument("--model", default="deepseek-v4-flash:0731")
    parser.add_argument(
        "--scenario",
        choices=("tool_loop", "cross_turn", "instruction"),
        default="cross_turn",
    )
    parser.add_argument("--repeats", type=int, default=3)
    parser.add_argument(
        "--policy", choices=("auto", "none", "current_run", "full_history"), default="auto"
    )
    parser.add_argument("--api-key-env", default="OLLAMA_API_KEY")
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR)
    parser.add_argument("--effort", default="max", help="reasoning_effort / think value.")
    args = parser.parse_args(argv)

    api_key = _load_api_key(args.api_key_env, args.data_dir)
    print(f"api key length: {len(api_key)}")
    print(
        f"provider: {args.provider} | model: {args.model} | "
        f"scenario: {args.scenario} | policy: {args.policy}"
    )

    adapter = _build_adapter(args.provider, args.model, api_key)
    policy: str | None = None if args.policy == "auto" else args.policy
    asyncio.run(_run_exact_probe(adapter, args.model, args.scenario, args.repeats, policy))
    return 0


if __name__ == "__main__":
    sys.exit(main())
