#!/usr/bin/env python
"""Live-probe background completion delivery against configured Provider Models.

The harness makes the first Model step deterministic: it synthesizes one Tool Call,
executes a probe Tool that submits three Bash-shaped completion notices, then sends
the next request through the real configured Provider adapter. It prints structural
measurements only — never credentials, prompts, completion bodies, generated text,
Tool arguments, or raw Provider responses.

Examples:
    python scripts/probe_background_completion.py
    python scripts/probe_background_completion.py --target openai --mode stream
    python scripts/probe_background_completion.py --repeat 3
"""

from __future__ import annotations

import argparse
import asyncio
import copy
import json
import secrets
import tempfile
import time
from collections.abc import AsyncIterator
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, cast

from core.agents import Agent
from core.automation import TriggerService
from core.chat import ChatLoop, ChatLoopDependencies, ChatSessionManager
from core.prompts import PinnedSkillCatalog
from core.providers.accounts import ConnectionRef
from core.runs import ChatRunManager, Run
from core.runtime.runtime import Runtime
from core.tools import ToolAccess, ToolContext, ToolRegistry, tool_success
from core.tools.change_tracker import ChangeTracker
from core.tools.file_state import FileReadState
from core.utils.config import Config

JsonObject = dict[str, Any]

PROBE_AGENT_ID = "background-completion-probe"
PROBE_SESSION_ID = "probe-session"
PROBE_TOOL_NAME = "completion_probe"
PROBE_TOOL_CALL_ID = "call_background_completion_probe"
NOTICE_COUNT = 3
DEFAULT_TIMEOUT_SECONDS = 300.0


@dataclass(frozen=True)
class ProbeTarget:
    name: str
    provider: str
    connection: str
    model: str

    @property
    def agent_model(self) -> str:
        local_connection = self.connection.removeprefix(f"{self.provider}:")
        return f"{self.provider}/{self.model}::{local_connection}"


TARGETS = {
    "opencode-go": ProbeTarget(
        name="opencode-go",
        provider="opencode-go",
        connection="opencode-go:api-key",
        model="deepseek-v4-flash",
    ),
    "openai": ProbeTarget(
        name="openai",
        provider="openai",
        connection="openai:subscription",
        model="gpt-5.6-luna",
    ),
}


class _ProbeAgentResolver:
    def __init__(self, agent: Agent) -> None:
        self._agent = agent

    def resolve_agent(
        self,
        project_id: str | None,
        agent_id: str,
        *,
        run_overrides: Any | None = None,
    ) -> Agent:
        if project_id is not None or agent_id != self._agent.id or run_overrides is not None:
            raise ValueError("background completion probe received an unexpected Agent target")
        return self._agent


class _EmptyProjects:
    def get(self, project_id: str) -> Any:
        raise KeyError(project_id)


class _EmptySkills:
    def list_all(self) -> list[Any]:
        return []

    def filter_allowed(self, _allowed_skills: list[str]) -> list[Any]:
        return []


class _ProbePromptManager:
    def __init__(self, tools: ToolRegistry, repository_root: Path) -> None:
        self._tools = tools
        self.vbot_root = repository_root

    def provider_tool_definitions(
        self,
        agent: Agent,
        *,
        session_tool_grants: tuple[str, ...] = (),
        **_kwargs: Any,
    ) -> list[JsonObject]:
        return self._tools.provider_definitions(
            list(agent.tool_access.allowed),
            session_grants=session_tool_grants,
        )

    def build_system_prompt(self, _agent: Agent, **_kwargs: Any) -> str:
        return (
            "This is a background-completion delivery probe. The preceding Assistant Tool Call "
            "was generated by the deterministic harness. Do not call any Tool. Read the trusted "
            "System Reminder after the Tool Result and answer with only its verification token."
        )

    def render_skill_catalog(self, _agent: Agent, _skills: Any) -> PinnedSkillCatalog:
        return PinnedSkillCatalog(catalog_text="")

    def render_working_project_context(self, _context: Any, **_kwargs: Any) -> str:
        return ""


class _NoopProcessManager:
    def cancel_scope(self, _scope_key: str) -> None:
        return None


class _SyntheticFirstStepAdapter:
    """Inject one deterministic Tool Call, then delegate to the real Adapter."""

    def __init__(self, delegate: Any) -> None:
        self._delegate = delegate
        self._synthetic_sent = False
        self._synthetic_response: JsonObject = {"probe_synthetic_response": True}
        self.synthetic_request_count = 0
        self.live_request_count = 0
        self.live_request_messages: list[list[JsonObject]] = []

    async def send(
        self,
        messages: list[JsonObject],
        *,
        model_id: str,
        **kwargs: Any,
    ) -> JsonObject:
        if not self._synthetic_sent:
            self._synthetic_sent = True
            self.synthetic_request_count += 1
            return self._synthetic_response
        self.live_request_count += 1
        self.live_request_messages.append(copy.deepcopy(messages))
        return cast(
            JsonObject,
            await self._delegate.send(messages, model_id=model_id, **kwargs),
        )

    def normalize_response(self, response: JsonObject, *, model_id: str) -> JsonObject:
        if response is self._synthetic_response:
            return {
                "content": None,
                "reasoning": None,
                "tool_calls": [
                    {
                        "id": PROBE_TOOL_CALL_ID,
                        "name": PROBE_TOOL_NAME,
                        "arguments": {},
                    }
                ],
                "terminal_outcome": "tool_calls",
            }
        return cast(
            JsonObject,
            self._delegate.normalize_response(response, model_id=model_id),
        )

    async def stream(
        self,
        messages: list[JsonObject],
        *,
        model_id: str,
        **kwargs: Any,
    ) -> AsyncIterator[JsonObject]:
        if not self._synthetic_sent:
            self._synthetic_sent = True
            self.synthetic_request_count += 1
            yield {
                "type": "tool_call_delta",
                "slot": 0,
                "id": PROBE_TOOL_CALL_ID,
                "name_delta": PROBE_TOOL_NAME,
                "arguments_delta": "{}",
            }
            yield {"type": "finish", "reason": "tool_calls"}
            return
        self.live_request_count += 1
        self.live_request_messages.append(copy.deepcopy(messages))
        async for delta in self._delegate.stream(messages, model_id=model_id, **kwargs):
            yield delta

    def reasoning_replay_policy(self, model_id: str) -> str:
        return str(self._delegate.reasoning_replay_policy(model_id))

    def wire_media_support(self, model_id: str) -> frozenset[str]:
        return frozenset(self._delegate.wire_media_support(model_id))

    def request_context_kwargs(self, **kwargs: Any) -> JsonObject:
        return dict(self._delegate.request_context_kwargs(**kwargs))

    def set_debug_context(self, context: Any) -> None:
        if hasattr(self._delegate, "set_debug_context"):
            self._delegate.set_debug_context(context)

    async def aclose(self) -> None:
        close = getattr(self._delegate, "aclose", None)
        if close is not None:
            await close()


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--target",
        choices=("all", *TARGETS),
        default="all",
        help="Configured live target to probe; default probes both required Models.",
    )
    parser.add_argument(
        "--mode",
        choices=("both", "stream", "nonstream"),
        default="both",
        help="ChatLoop request mode; both exercises both progression paths.",
    )
    parser.add_argument("--repeat", type=int, default=1)
    parser.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT_SECONDS)
    parser.add_argument("--data-dir", type=Path)
    return parser


def _start_probe_runtime(runtime: Runtime) -> None:
    """Bootstrap Provider dependencies without starting operational services."""

    def _do_not_start() -> None:
        return None

    for hook_name in (
        "_start_process_manager",
        "_start_channel_service",
        "_start_cron_service",
        "_start_provider_usage_service",
    ):
        setattr(runtime, hook_name, _do_not_start)
    runtime.start()


def _probe_agent(target: ProbeTarget, workspace: Path) -> Agent:
    timestamp = datetime.now(UTC).isoformat()
    return Agent(
        id=PROBE_AGENT_ID,
        name="Background Completion Probe",
        model=target.agent_model,
        fallback_model="",
        workspace=str(workspace),
        temperature=0.0,
        thinking_effort="high",
        tool_access=ToolAccess(mode="selected", allowed=(PROBE_TOOL_NAME,)),
        allowed_skills=[],
        created_at=timestamp,
        updated_at=timestamp,
        memory_prompt_mode="off",
    )


def _selected_targets(name: str) -> list[ProbeTarget]:
    if name == "all":
        return list(TARGETS.values())
    return [TARGETS[name]]


def _selected_modes(name: str) -> list[bool]:
    if name == "both":
        return [False, True]
    return [name == "stream"]


def _message_roles(messages: list[JsonObject]) -> list[str]:
    return [str(message.get("role")) for message in messages]


def _completion_request_measurements(
    messages: list[JsonObject],
    verification_token: str,
) -> dict[str, Any]:
    roles = _message_roles(messages)
    reminder_indexes = [
        index
        for index, message in enumerate(messages)
        if message.get("role") == "user"
        and isinstance(message.get("content"), str)
        and "<system-reminder>" in str(message["content"])
        and verification_token in str(message["content"])
    ]
    reminder_index = reminder_indexes[0] if len(reminder_indexes) == 1 else None
    tool_index = max(
        (index for index, message in enumerate(messages) if message.get("role") == "tool"),
        default=-1,
    )
    assistant_tool_index = max(
        (
            index
            for index, message in enumerate(messages)
            if message.get("role") == "assistant" and message.get("tool_calls")
        ),
        default=-1,
    )
    return {
        "request_roles": roles,
        "one_completion_reminder": len(reminder_indexes) == 1,
        "tool_cycle_contiguous": assistant_tool_index >= 0
        and tool_index == assistant_tool_index + 1,
        "reminder_after_tool_result": reminder_index == tool_index + 1,
    }


def _result_passed(result: JsonObject) -> bool:
    required_true = (
        "completion_acknowledged",
        "one_completion_note_persisted",
        "one_completion_reminder",
        "tool_cycle_contiguous",
        "reminder_after_tool_result",
        "verification_token_observed",
        "no_follow_up_run",
        "session_order_valid",
    )
    return (
        result.get("status") == "completed"
        and result.get("synthetic_requests") == 1
        and result.get("live_provider_requests") == 1
        and result.get("iterations") == 2
        and all(result.get(name) is True for name in required_true)
    )


async def _run_case(
    source_runtime: Runtime,
    target: ProbeTarget,
    *,
    streaming: bool,
    case_root: Path,
    timeout_seconds: float,
) -> JsonObject:
    started = time.monotonic()
    verification_token = f"VBOT_COMPLETION_{secrets.token_hex(12).upper()}"
    workspace = case_root / "workspace"
    workspace.mkdir(parents=True)
    sessions = ChatSessionManager(case_root / "sessions")
    sessions.create(PROBE_AGENT_ID, session_id=PROBE_SESSION_ID)
    run_manager = ChatRunManager()
    started_runs: list[Run] = []
    remove_run_listener = run_manager.add_run_started_callback(started_runs.append)
    tools = ToolRegistry()
    agent = _probe_agent(target, workspace)
    prompt_manager = _ProbePromptManager(tools, Path(__file__).resolve().parents[1])
    skills = _EmptySkills()
    trigger_service: TriggerService | None = None
    wrapped_adapters: list[_SyntheticFirstStepAdapter] = []
    completion_futures: list[asyncio.Future[None]] = []

    def deliver_background_completions(run: Run, session: Any) -> bool:
        if trigger_service is None:
            raise RuntimeError("completion TriggerService is not initialized")
        return trigger_service.deliver_background_completions(run, session)

    def get_adapter(connection: ConnectionRef) -> _SyntheticFirstStepAdapter:
        if (
            connection.provider_id != target.provider
            or connection.connection_id != target.connection
        ):
            raise ValueError("background completion probe resolved an unexpected Provider route")
        wrapped = _SyntheticFirstStepAdapter(source_runtime.get_adapter(connection))
        wrapped_adapters.append(wrapped)
        return wrapped

    async def image_understanding_available() -> bool:
        return False

    dependencies = ChatLoopDependencies(
        agent_resolver=cast(Any, _ProbeAgentResolver(agent)),
        projects=cast(Any, _EmptyProjects()),
        providers=source_runtime.providers,
        models=source_runtime.models,
        provider_credentials=source_runtime.provider_credentials,
        sessions=sessions,
        run_manager=run_manager,
        tools=tools,
        process_manager=cast(Any, _NoopProcessManager()),
        file_read_state=FileReadState(),
        change_tracker=ChangeTracker(),
        storage=source_runtime.storage,
        get_extension_registry=lambda: None,
        get_system_prompts=cast(Any, lambda: prompt_manager),
        get_adapter=cast(Any, get_adapter),
        resolve_skills=cast(Any, lambda _project_id, _agent_id: skills),
        refresh_skills=cast(Any, lambda _project_id, _agent_id: skills),
        get_local_context_windows=source_runtime.local_context_windows,
        image_understanding_available=image_understanding_available,
        deliver_background_completions=deliver_background_completions,
    )
    chat_loop = ChatLoop(dependencies, streaming=streaming)
    trigger_service = TriggerService(
        chat_loop,
        run_manager,
        source_runtime,
        trigger_chat_loop=chat_loop,
        sessions=sessions,
    )

    def completion_probe(context: ToolContext, _arguments: JsonObject) -> JsonObject:
        assert trigger_service is not None
        for index in range(NOTICE_COUNT):
            token_line = f"Verification token: {verification_token}" if index == 0 else ""
            completion_futures.append(
                trigger_service.submit_completion(
                    PROBE_AGENT_ID,
                    PROBE_SESSION_ID,
                    notice_id=f"bash:{context.run_id}:{index}",
                    origin_run_id=context.run_id,
                    body=(
                        f"### Bash process {index + 1} — completed\n"
                        f"Background command {index + 1} finished successfully.\n{token_line}"
                    ).rstrip(),
                )
            )
        return tool_success({"status": "running", "delivery": "automatic"})

    tools.register(
        PROBE_TOOL_NAME,
        "Simulate Bash background completions for the live Provider probe.",
        {"type": "object"},
        completion_probe,
    )

    try:
        async with asyncio.timeout(timeout_seconds):
            assistant = await chat_loop.send(
                PROBE_AGENT_ID,
                "Wait for the completion report, then return its verification token.",
                session_id=PROBE_SESSION_ID,
            )
            if completion_futures:
                await asyncio.gather(*completion_futures)
            await asyncio.sleep(0)
            await asyncio.sleep(0)
    except Exception as error:  # noqa: BLE001 - live diagnostics classify every failure
        return {
            "provider": target.provider,
            "connection": target.connection,
            "model": target.model,
            "mode": "stream" if streaming else "nonstream",
            "status": "error",
            "error_type": type(error).__name__,
            "elapsed_seconds": round(time.monotonic() - started, 3),
        }
    finally:
        remove_run_listener()

    wrapper = wrapped_adapters[0] if len(wrapped_adapters) == 1 else None
    live_messages = (
        wrapper.live_request_messages[0]
        if wrapper is not None and len(wrapper.live_request_messages) == 1
        else []
    )
    request_measurements = _completion_request_measurements(
        live_messages,
        verification_token,
    )
    persisted = sessions.get(PROBE_AGENT_ID, PROBE_SESSION_ID).load()
    persisted_roles = [message.role for message in persisted]
    completion_notes = [
        message
        for message in persisted
        if message.role == "note"
        and isinstance(message.content, str)
        and verification_token in message.content
    ]
    primary_run = started_runs[0] if started_runs else None
    assistant_content = assistant.content if isinstance(assistant.content, str) else ""
    result: JsonObject = {
        "provider": target.provider,
        "connection": target.connection,
        "model": target.model,
        "mode": "stream" if streaming else "nonstream",
        "status": primary_run.status.value if primary_run is not None else "missing_run",
        "error_type": None,
        "elapsed_seconds": round(time.monotonic() - started, 3),
        "synthetic_requests": wrapper.synthetic_request_count if wrapper is not None else 0,
        "live_provider_requests": wrapper.live_request_count if wrapper is not None else 0,
        "iterations": primary_run.iteration_count if primary_run is not None else 0,
        "completion_acknowledged": (
            len(completion_futures) == NOTICE_COUNT
            and all(future.done() and not future.cancelled() for future in completion_futures)
        ),
        "one_completion_note_persisted": len(completion_notes) == 1,
        "verification_token_observed": verification_token in assistant_content,
        "no_follow_up_run": len(started_runs) == 1,
        "session_order_valid": persisted_roles
        == ["user", "assistant", "tool", "note", "assistant", "run_summary"],
        "persisted_roles": persisted_roles,
        **request_measurements,
    }
    result["passed"] = _result_passed(result)
    return result


async def _run(args: argparse.Namespace) -> int:
    if args.repeat < 1:
        raise ValueError("--repeat must be at least 1")
    if args.timeout <= 0:
        raise ValueError("--timeout must be positive")

    source_runtime = Runtime(Config(data_dir=args.data_dir))
    _start_probe_runtime(source_runtime)
    results: list[JsonObject] = []
    try:
        for repetition in range(1, args.repeat + 1):
            for target in _selected_targets(str(args.target)):
                if not source_runtime.provider_credentials.is_usable(
                    target.provider,
                    target.connection,
                ):
                    results.append(
                        {
                            "provider": target.provider,
                            "connection": target.connection,
                            "model": target.model,
                            "repetition": repetition,
                            "status": "unavailable",
                            "passed": False,
                        }
                    )
                    continue
                for streaming in _selected_modes(str(args.mode)):
                    with tempfile.TemporaryDirectory(
                        prefix="vbot-background-completion-probe-"
                    ) as temporary_dir:
                        result = await _run_case(
                            source_runtime,
                            target,
                            streaming=streaming,
                            case_root=Path(temporary_dir),
                            timeout_seconds=float(args.timeout),
                        )
                    result["repetition"] = repetition
                    results.append(result)
    finally:
        await source_runtime.aclose()

    passed = bool(results) and all(result.get("passed") is True for result in results)
    report = {
        "probe": "background_completion_request_boundary",
        "passed": passed,
        "cases": len(results),
        "results": results,
    }
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0 if passed else 1


def main() -> int:
    return asyncio.run(_run(_parser().parse_args()))


if __name__ == "__main__":
    raise SystemExit(main())
