"""Incrementally indexed statistics aggregation over persisted Sessions."""

from __future__ import annotations

from core.statistics._sources import (
    AgentDirectory,
    ProjectDirectory,
    SessionSource,
)
from core.statistics.report import (
    AgentActivity,
    AgentRunCount,
    CacheBreakIncident,
    CacheSection,
    CompactionReclaimStats,
    CompactionSessionStat,
    CompactionsSection,
    CompactionStrategyCount,
    CountEntry,
    DailyCount,
    DailyTrendPoint,
    DurationStats,
    ErrorsSection,
    HourCount,
    LongestRun,
    ModelUsage,
    OverviewSection,
    ProviderUsage,
    RunActivity,
    RunActivityReport,
    RunsSection,
    RunStatusCounts,
    SessionCacheUsage,
    SessionRunCount,
    StatisticsReport,
    SuspectedCacheBreaks,
    ToolSessionCount,
    ToolsSection,
    ToolStat,
    UsageDailyPoint,
    UsageSection,
    UsageTotals,
    WindowInfo,
)
from core.statistics.skills import (
    SkillByAgentCount,
    SkillInventorySource,
    SkillsSection,
    SkillUsageStat,
)
from core.statistics.statistics import (
    StatisticsService,
)

__all__ = [
    "AgentActivity",
    "AgentDirectory",
    "AgentRunCount",
    "CacheBreakIncident",
    "CacheSection",
    "CompactionReclaimStats",
    "CompactionSessionStat",
    "CompactionsSection",
    "CompactionStrategyCount",
    "CountEntry",
    "DailyCount",
    "DailyTrendPoint",
    "DurationStats",
    "ErrorsSection",
    "HourCount",
    "LongestRun",
    "ModelUsage",
    "OverviewSection",
    "ProjectDirectory",
    "ProviderUsage",
    "RunActivity",
    "RunActivityReport",
    "RunStatusCounts",
    "RunsSection",
    "SessionCacheUsage",
    "SessionRunCount",
    "SessionSource",
    "SkillByAgentCount",
    "SkillInventorySource",
    "SkillUsageStat",
    "SkillsSection",
    "StatisticsReport",
    "StatisticsService",
    "SuspectedCacheBreaks",
    "ToolSessionCount",
    "ToolStat",
    "ToolsSection",
    "UsageDailyPoint",
    "UsageSection",
    "UsageTotals",
    "WindowInfo",
]
