"""Session recall read-model backends."""

from core.recall.canonical import CanonicalSessionRecallBackend
from core.recall.hybrid import HybridRecallBackend
from core.recall.recall import (
    DEFAULT_RECALL_BACKEND,
    FIRST_PARTY_RECALL_BACKENDS,
    RECALL_BACKEND_CANONICAL_SCAN,
    RECALL_BACKEND_HYBRID,
    RECALL_BACKEND_SQLITE_FTS,
    RECALL_BACKEND_VECTOR,
    JsonObject,
    RecallBackend,
    RecallBackendContext,
    RecallBackendFactory,
    RecallBackendRegistry,
    RecallMatchMode,
    RecallOrder,
    RecallRequest,
    RecallResultType,
    RecallSearchCapabilities,
    RecallSearchError,
    RecallSearchHit,
    RecallSearchPage,
    RecallSearchRequest,
    RecallSortMode,
    SupportsRecallSearch,
    SupportsSessionRemoval,
)
from core.recall.sqlite_fts import SqliteFtsRecallBackend
from core.recall.vector import VectorRecallBackend
from core.recall.vector_store import (
    ChunkVectorRecord,
    VectorHeader,
    VectorStore,
    VectorStoreError,
)

__all__ = [
    "DEFAULT_RECALL_BACKEND",
    "FIRST_PARTY_RECALL_BACKENDS",
    "HybridRecallBackend",
    "JsonObject",
    "CanonicalSessionRecallBackend",
    "RECALL_BACKEND_HYBRID",
    "RECALL_BACKEND_CANONICAL_SCAN",
    "RECALL_BACKEND_SQLITE_FTS",
    "RECALL_BACKEND_VECTOR",
    "RecallBackend",
    "RecallBackendContext",
    "RecallBackendFactory",
    "RecallBackendRegistry",
    "RecallMatchMode",
    "RecallOrder",
    "RecallRequest",
    "RecallResultType",
    "RecallSearchError",
    "RecallSearchCapabilities",
    "RecallSearchHit",
    "RecallSearchPage",
    "RecallSearchRequest",
    "RecallSortMode",
    "SupportsRecallSearch",
    "SupportsSessionRemoval",
    "ChunkVectorRecord",
    "SqliteFtsRecallBackend",
    "VectorHeader",
    "VectorRecallBackend",
    "VectorStore",
    "VectorStoreError",
]
