"""Task-model bindings, discovery, and specialized task execution."""

from core.model_tasks.constants import (
    SPEECH_TASK_TYPES,
    SUPPORTED_TASK_TYPES,
    TASK_IMAGE_GENERATION,
    TASK_IMAGE_UNDERSTANDING,
    TASK_MUSIC_GENERATION,
    TASK_SPEECH_TO_TEXT,
    TASK_TEXT_EMBEDDING,
    TASK_TEXT_TO_SPEECH,
    TASK_VIDEO_GENERATION,
)
from core.model_tasks.embeddings import (
    EmbeddingConfigurationError,
    EmbeddingError,
    EmbeddingExecutionError,
    EmbeddingPurpose,
    EmbeddingResult,
    EmbeddingService,
    EmbeddingSpaceIdentity,
    EmbeddingUnsupportedTargetError,
)
from core.model_tasks.embeddings_providers import EmbeddingUsage, ProviderEmbeddingClient
from core.model_tasks.image import (
    ImageConfigurationError,
    ImageError,
    ImageExecutionError,
    ImageInputError,
    ImageNotFoundError,
    ImageOutcomeUnknownError,
    ImageReadError,
    ImageService,
    ImageTooLargeError,
    ImageUnderstandingUnavailableError,
    ImageUnsupportedMediaTypeError,
    ImageUnsupportedTargetError,
)
from core.model_tasks.image_providers import ProviderImageClient
from core.model_tasks.image_types import (
    ImageArtifact,
    ImageGenerationResult,
    ImageUnderstandingResult,
    ImageUnderstandingRunContext,
)
from core.model_tasks.local_targets import (
    DEFAULT_LOCAL_TASK_TARGET_REGISTRY,
    LocalTaskTargetDescriptor,
    LocalTaskTargetError,
    LocalTaskTargetRegistry,
)
from core.model_tasks.model_tasks import (
    TaskModelBinding,
    TaskModelError,
    TaskModelService,
    TaskModelTarget,
    TaskModelTargetRef,
    TaskModelValidationError,
    parse_task_model_target_id,
    public_provider_target_id,
    validate_task_type,
)
from core.model_tasks.music import (
    MusicConfigurationError,
    MusicError,
    MusicExecutionError,
    MusicOutcomeUnknownError,
    MusicService,
)
from core.model_tasks.music_providers import ProviderMusicClient
from core.model_tasks.music_types import MusicGenerationResult
from core.model_tasks.options import (
    TaskModelOptionChoice,
    TaskModelOptionField,
    TaskModelOptionSchema,
    option_schema_for,
    validate_task_model_options,
)
from core.model_tasks.speech import (
    SpeechArtifact,
    SpeechConfigurationError,
    SpeechError,
    SpeechExecutionError,
    SpeechOutcomeUnknownError,
    SpeechService,
    SpeechUnsupportedTargetError,
)
from core.model_tasks.speech_local import LocalSpeechError, LocalSpeechExecutor
from core.model_tasks.speech_providers import ProviderSpeechClient, audio_format_from
from core.model_tasks.speech_types import SpeechSynthesisResult, SpeechTranscriptionResult
from core.model_tasks.video import (
    VideoConfigurationError,
    VideoError,
    VideoExecutionError,
    VideoOutcomeUnknownError,
    VideoService,
)
from core.model_tasks.video_providers import ProviderVideoClient
from core.model_tasks.video_types import VideoGenerationResult

__all__ = [
    "DEFAULT_LOCAL_TASK_TARGET_REGISTRY",
    "EmbeddingConfigurationError",
    "EmbeddingError",
    "EmbeddingExecutionError",
    "EmbeddingPurpose",
    "EmbeddingResult",
    "EmbeddingService",
    "EmbeddingSpaceIdentity",
    "EmbeddingUnsupportedTargetError",
    "EmbeddingUsage",
    "ImageArtifact",
    "ImageConfigurationError",
    "ImageError",
    "ImageExecutionError",
    "ImageGenerationResult",
    "ImageInputError",
    "ImageNotFoundError",
    "ImageOutcomeUnknownError",
    "ImageReadError",
    "ImageService",
    "ImageTooLargeError",
    "ImageUnderstandingResult",
    "ImageUnderstandingRunContext",
    "ImageUnderstandingUnavailableError",
    "ImageUnsupportedMediaTypeError",
    "ImageUnsupportedTargetError",
    "LocalSpeechError",
    "LocalSpeechExecutor",
    "LocalTaskTargetDescriptor",
    "LocalTaskTargetError",
    "LocalTaskTargetRegistry",
    "MusicConfigurationError",
    "MusicError",
    "MusicExecutionError",
    "MusicGenerationResult",
    "MusicOutcomeUnknownError",
    "MusicService",
    "ProviderEmbeddingClient",
    "ProviderImageClient",
    "ProviderMusicClient",
    "ProviderSpeechClient",
    "SPEECH_TASK_TYPES",
    "SUPPORTED_TASK_TYPES",
    "SpeechArtifact",
    "SpeechConfigurationError",
    "SpeechError",
    "SpeechExecutionError",
    "SpeechOutcomeUnknownError",
    "SpeechService",
    "SpeechSynthesisResult",
    "SpeechTranscriptionResult",
    "SpeechUnsupportedTargetError",
    "TASK_IMAGE_GENERATION",
    "TASK_IMAGE_UNDERSTANDING",
    "TASK_MUSIC_GENERATION",
    "TASK_SPEECH_TO_TEXT",
    "TASK_TEXT_EMBEDDING",
    "TASK_TEXT_TO_SPEECH",
    "TASK_VIDEO_GENERATION",
    "TaskModelBinding",
    "TaskModelError",
    "TaskModelOptionChoice",
    "TaskModelOptionField",
    "TaskModelOptionSchema",
    "TaskModelService",
    "TaskModelTarget",
    "TaskModelTargetRef",
    "TaskModelValidationError",
    "VideoConfigurationError",
    "VideoError",
    "VideoExecutionError",
    "VideoGenerationResult",
    "VideoOutcomeUnknownError",
    "VideoService",
    "ProviderVideoClient",
    "audio_format_from",
    "option_schema_for",
    "parse_task_model_target_id",
    "public_provider_target_id",
    "validate_task_model_options",
    "validate_task_type",
]
