"""Shared task-model vocabulary."""

from __future__ import annotations

TASK_SPEECH_TO_TEXT = "speech_to_text"
TASK_TEXT_TO_SPEECH = "text_to_speech"
TASK_IMAGE_UNDERSTANDING = "image_understanding"
TASK_IMAGE_GENERATION = "image_generation"
TASK_VIDEO_GENERATION = "video_generation"
TASK_MUSIC_GENERATION = "music_generation"
TASK_TEXT_EMBEDDING = "text_embedding"

SUPPORTED_TASK_TYPES = frozenset(
    {
        TASK_SPEECH_TO_TEXT,
        TASK_TEXT_TO_SPEECH,
        TASK_IMAGE_UNDERSTANDING,
        TASK_IMAGE_GENERATION,
        TASK_VIDEO_GENERATION,
        TASK_MUSIC_GENERATION,
        TASK_TEXT_EMBEDDING,
    }
)

SPEECH_TASK_TYPES = frozenset({TASK_SPEECH_TO_TEXT, TASK_TEXT_TO_SPEECH})

TRANSCRIPTION_AUDIO_PROFILE_COMPATIBILITY = "compatibility"
TRANSCRIPTION_AUDIO_PROFILE_HIGH_QUALITY = "high_quality"
TRANSCRIPTION_AUDIO_PROFILE_CUSTOM = "custom"
SUPPORTED_TRANSCRIPTION_AUDIO_PROFILES = frozenset(
    {
        TRANSCRIPTION_AUDIO_PROFILE_COMPATIBILITY,
        TRANSCRIPTION_AUDIO_PROFILE_HIGH_QUALITY,
        TRANSCRIPTION_AUDIO_PROFILE_CUSTOM,
    }
)
SUPPORTED_TRANSCRIPTION_AUDIO_FORMATS = frozenset({"wav", "flac"})
SUPPORTED_TRANSCRIPTION_AUDIO_SAMPLE_RATES = frozenset({16_000, 24_000, 48_000})
TRANSCRIPTION_AUDIO_PRESETS = {
    TRANSCRIPTION_AUDIO_PROFILE_COMPATIBILITY: {
        "format": "wav",
        "sample_rate_hz": 16_000,
    },
    TRANSCRIPTION_AUDIO_PROFILE_HIGH_QUALITY: {
        "format": "flac",
        "sample_rate_hz": 48_000,
    },
}
DEFAULT_TRANSCRIPTION_AUDIO_SETTINGS = {
    "profile": TRANSCRIPTION_AUDIO_PROFILE_COMPATIBILITY,
    **TRANSCRIPTION_AUDIO_PRESETS[TRANSCRIPTION_AUDIO_PROFILE_COMPATIBILITY],
}
