"""Computer Use on Windows: the platform-independent rules of the Windows desktop target.

Key and text planning, SendInput coordinates, app identity and categories, the
Start-menu index and display naming. Nothing here sends input, takes screenshots
or starts processes, so the suite runs on every platform.
"""

from __future__ import annotations

import ctypes
import logging
import threading

import pytest

from resources.extensions.computer_use import _keys, _win_apps, _win_input
from resources.extensions.computer_use._win32 import Monitor
from resources.extensions.computer_use._win_apps import StartApps, StartIndex, StartRow
from resources.extensions.computer_use.target import AppInfo
from resources.extensions.computer_use.windows_target import name_displays

WINDOWS = "C:\\Windows"
CODE = "C:\\Users\\Ada\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe"
CALCULATOR = "Microsoft.WindowsCalculator_8wekyb3d8bbwe"
TERMINAL = "Microsoft.WindowsTerminal_8wekyb3d8bbwe"


def start_rows() -> list[StartRow]:
    return [
        StartRow("Visual Studio Code", "Microsoft.VisualStudioCode", CODE),
        StartRow("Code", "Microsoft.AutoGenerated.{0A1B}", CODE),  # a shortcut with arguments
        StartRow("Downloads", "{374DE290}\\Downloads", f"{WINDOWS}\\explorer.exe"),
        StartRow("File Explorer", "Microsoft.Windows.Explorer"),
        StartRow("vBot", "vBot.Desktop", "C:\\Program Files\\vBot\\vBot.exe"),
        StartRow("Calculator", f"{CALCULATOR}!App", "", CALCULATOR, "CalculatorApp.exe"),
        StartRow("Terminal", f"{TERMINAL}!App", "", TERMINAL),
        StartRow("Services", "services.msc", f"{WINDOWS}\\system32\\services.msc"),
        StartRow("Readme", "C:\\Docs\\readme.txt", "C:\\Docs\\readme.txt"),
        StartRow("Website", "https://example.com", "https://example.com"),
        StartRow("Tool", "A.Tool", "C:\\A\\tool.exe"),
        StartRow("Tool", "B.Tool", "C:\\B\\tool.exe"),
    ]


def running(name: str, path: str) -> AppInfo:
    return AppInfo(name, _win_apps.identity_keys(path, None), True, True)


def test_every_canonical_key_has_a_virtual_key():
    assert {*_keys.MODIFIERS, *_keys.NAMED_KEYS} <= _win_input.NAMED_KEYS.keys()
    assert set(_win_input.MODIFIER_KEYS) == set(_keys.MODIFIERS)


def test_input_records_have_the_native_size():
    # SendInput rejects every event when its size argument differs from the native INPUT.
    assert ctypes.sizeof(_win_input.Input) == (40 if ctypes.sizeof(ctypes.c_void_p) == 8 else 28)


@pytest.mark.parametrize(
    "result,decoded",
    [
        (0x0041, (0x41, ())),
        (0x0141, (0x41, ("shift",))),
        (0x0651, (0x51, ("ctrl", "alt"))),  # AltGr characters such as @ on a German layout
        (0x0731, (0x31, ("shift", "ctrl", "alt"))),
        (-1, None),  # the layout has no key for the character
        (0xFFFF, None),
        (0x0841, None),  # needs a Kana or OEM shift state a chord cannot press
    ],
)
def test_key_scan_results_become_a_key_and_its_modifiers(result, decoded):
    assert _win_input.decode_key_scan(result) == decoded


@pytest.mark.parametrize(
    "origin,size", [(0, 1), (0, 1080), (-1920, 4480), (-3840, 7680), (270, 1440)]
)
def test_absolute_mouse_coordinates_land_on_the_requested_pixel(origin, size):
    for position in range(origin, origin + size):
        normalized = _win_input.absolute_coordinate(position, origin, size)
        assert 0 <= normalized <= 65535
        assert origin + normalized * size // 65536 == position  # how Windows maps it back


def test_typed_text_presses_enter_once_per_line_break_and_tab_for_tabs():
    assert _win_input.text_units("a\r\nb\rc\nd\te") == [
        (ord("a"),), "enter", (ord("b"),), "enter", (ord("c"),), "enter", (ord("d"),), "tab",
        (ord("e"),),
    ]  # fmt: skip
    # Each character's UTF-16 code units, sent together.
    assert _win_input.text_units("ä😀") == [(0xE4,), (0xD83D, 0xDE00)]


@pytest.mark.parametrize(
    "path,family,keys",
    [
        (CODE, None, {CODE.lower(), "exe:code.exe"}),
        # A generic host runs many apps; only its full path identifies one of them.
        ("C:\\Python314\\python.exe", None, {"c:\\python314\\python.exe"}),
        (
            "C:\\Program Files\\WindowsApps\\Calc\\CalculatorApp.exe",
            CALCULATOR,
            {
                "c:\\program files\\windowsapps\\calc\\calculatorapp.exe",
                "exe:calculatorapp.exe",
                f"pkg:{CALCULATOR.lower()}",
            },
        ),
        (None, None, set()),  # the process is gone or cannot be read
    ],
)
def test_identity_keys_of_a_process(path, family, keys):
    assert _win_apps.identity_keys(path, family) == keys


@pytest.mark.parametrize(
    "executable,own",
    [("vBot.exe", True), ("vbot.server.exe", True), ("vbotx.exe", False), ("python.exe", False)],
)
def test_vbot_executables_are_recognized(executable, own):
    assert _win_apps.is_vbot_executable(executable) is own


@pytest.mark.parametrize(
    "children,hosted",
    [
        ([("ApplicationFrameTitleBarWindow", 10), ("Windows.UI.Core.CoreWindow", 22)], 22),
        ([("Windows.UI.Core.CoreWindow", 10)], 10),  # the frame's own core window
        ([], 10),  # a suspended app has no core window in its frame
    ],
)
def test_a_uwp_frame_belongs_to_the_process_of_its_core_window(children, hosted):
    assert _win_apps.hosted_process(10, children) == hosted


def test_start_index_lists_each_app_once_under_a_unique_name():
    index = StartIndex(start_rows(), WINDOWS)
    apps = {app.name: app for app in index.apps}

    assert [app.name for app in index.apps] == [
        "Calculator", "File Explorer", "Services", "Terminal", "Tool", "Tool (2)", "vBot",
        "Visual Studio Code",
    ]  # fmt: skip
    assert apps["Visual Studio Code"].keys == {CODE.lower(), "exe:code.exe"}
    assert apps["File Explorer"].app_id == "Microsoft.Windows.Explorer"
    assert apps["File Explorer"].keys == {f"{WINDOWS.lower()}\\explorer.exe", "exe:explorer.exe"}
    assert apps["vBot"].keys == {_win_apps.OWN_KEY}
    assert apps["Calculator"].keys == {f"pkg:{CALCULATOR.lower()}"}
    assert apps["Services"].keys == {f"{WINDOWS.lower()}\\system32\\mmc.exe"}
    assert apps["Tool"].keys == {"c:\\a\\tool.exe", "exe:tool.exe"}
    assert apps["Tool (2)"].keys == {"c:\\b\\tool.exe", "exe:tool.exe"}


@pytest.mark.parametrize(
    "keys,found",
    [
        (_win_apps.identity_keys(CODE, None), "Visual Studio Code"),
        # A copy elsewhere is the same app while its executable name is unique.
        (_win_apps.identity_keys("D:\\Portable\\Code.exe", None), "Visual Studio Code"),
        (_win_apps.identity_keys("C:\\B\\tool.exe", None), "Tool (2)"),
        (_win_apps.identity_keys("D:\\tool.exe", None), None),  # which Tool is ambiguous
        (_win_apps.identity_keys("C:\\Apps\\CalculatorApp.exe", CALCULATOR), "Calculator"),
        (_win_apps.identity_keys("C:\\Other\\other.exe", None), None),
    ],
)
def test_start_index_finds_the_app_of_running_keys(keys, found):
    app = StartIndex(start_rows(), WINDOWS).lookup(keys)
    assert (app.name if app else None) == found


def test_running_apps_merge_into_installed_apps_by_key_then_name():
    index = StartIndex(start_rows(), WINDOWS)
    apps = _win_apps.merge_apps(
        index.apps,
        [
            running("Visual Studio Code", CODE),
            running("Python", "C:\\Python314\\python.exe"),
            running("Python", "C:\\Project\\.venv\\Scripts\\python.exe"),
            _win_apps.OWN_APP,
        ],
    )
    by_name = {app.name: app for app in apps}

    assert [app.name for app in apps] == sorted(by_name, key=str.casefold)
    assert len(apps) == len(index.apps) + 1
    assert by_name["Visual Studio Code"].running
    assert not by_name["Calculator"].running
    assert by_name["Python"].keys == {
        "c:\\python314\\python.exe",
        "c:\\project\\.venv\\scripts\\python.exe",
    }
    assert by_name["vBot"].running and by_name["vBot"].launchable
    assert by_name["Calculator"].launchable


def test_start_apps_discover_once_per_period_without_blocking_callers():
    now = [0.0]
    discovered = [threading.Event(), threading.Event()]
    release = threading.Event()
    calls: list[int] = []

    def discover() -> list[StartRow]:
        calls.append(len(calls))
        discovered[min(len(calls), 2) - 1].set()
        if len(calls) > 1:
            release.wait(5)
            return [*start_rows(), StartRow("Paint", "Paint", "C:\\Paint\\paint.exe")]
        return start_rows()

    start = StartApps(discover, period=60, clock=lambda: now[0], windows_dir=WINDOWS)
    first = start.index(wait=5)
    assert {app.name for app in first.apps} >= {"Visual Studio Code"}
    now[0] = 59
    assert start.index() is first and len(calls) == 1

    now[0] = 60
    assert start.index() is first  # stale: the refresh runs in the background
    assert discovered[1].wait(5)
    release.set()
    _join_discovery()
    assert "Paint" in {app.name for app in start.index().apps}
    assert len(calls) == 2


def test_failed_start_discovery_yields_no_apps_and_warns_once(caplog):
    now = [0.0]

    def discover() -> list[StartRow]:
        raise OSError("powershell missing")

    start = StartApps(discover, period=60, clock=lambda: now[0], windows_dir=WINDOWS)
    with caplog.at_level(logging.WARNING, logger="vbot.extensions.computer_use"):
        assert start.index(wait=5).apps == ()
        now[0] = 120
        start.index()
        _join_discovery()

    warnings = [record.getMessage() for record in caplog.records]
    assert warnings == ["Start menu app discovery failed (error=OSError)"]


def test_displays_are_ordered_primary_first_with_unique_names():
    monitors = [
        Monitor("\\\\.\\DISPLAY3", 2560, 0, 4480, 1080, primary=False, dpi=96),
        Monitor("\\\\.\\DISPLAY1", -1920, 270, 0, 1350, primary=False, dpi=96),
        Monitor("\\\\.\\DISPLAY2", 0, 0, 2560, 1440, primary=True, dpi=120),
    ]
    names = {"\\\\.\\DISPLAY1": "LG ULTRAGEAR", "\\\\.\\DISPLAY2": "LG ULTRAGEAR"}

    displays = name_displays(monitors, names)

    assert [(display.name, display.id) for display in displays] == [
        ("LG ULTRAGEAR (1)", "\\\\.\\DISPLAY2"),
        ("LG ULTRAGEAR (2)", "\\\\.\\DISPLAY1"),
        ("Display 3", "\\\\.\\DISPLAY3"),
    ]
    assert (displays[0].width, displays[0].height, displays[0].scale_percent) == (2560, 1440, 125)
    assert (displays[1].left, displays[1].top, displays[1].scale_percent) == (-1920, 270, 100)


def _join_discovery() -> None:
    for thread in threading.enumerate():
        if thread.name == "computer-use-start-apps":
            thread.join(5)
